import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.dashboard.utils.db import get_full_trends_data, get_screener_data

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output" / "portfolio"


def get_trend_arrow(val_prev, val_latest):
    """Handles operations for get_trend_arrow."""
    if pd.isna(val_prev) or pd.isna(val_latest) or val_prev == 0:
        return "<font color='gray'>N/A</font>"

    pct_change = ((val_latest - val_prev) / abs(val_prev)) * 100

    if pct_change > 2.0:
        return f"<font color='green'><b>UP ({pct_change:+.1f}%)</b></font>"
    elif pct_change < -2.0:
        return f"<font color='red'><b>DOWN ({pct_change:+.1f}%)</b></font>"
    else:
        return f"<font color='gray'><b>FLAT ({pct_change:+.1f}%)</b></font>"


def build_portfolio_summary():
    """Handles operations for build_portfolio_summary."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    pdf_path = OUTPUT_DIR / "portfolio_summary.pdf"

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30,
    )
    styles = getSampleStyleSheet()

    # Custom Styles
    style_title = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.white,
        backColor=colors.HexColor("#1f497d"),
        alignment=1,
        spaceAfter=30,
        spaceBefore=0,
        borderPadding=20,
    )

    style_header = ParagraphStyle(
        "Header",
        parent=styles["Heading2"],
        fontSize=18,
        textColor=colors.HexColor("#1f497d"),
        alignment=0,
        spaceAfter=10,
    )

    style_normal = styles["Normal"]
    story = []

    # Title Page
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph("<b>NIFTY 100 Portfolio Summary</b>", style_title))
    story.append(
        Paragraph(
            "<b>Confidential Report</b><br/>Generated by NLP & Cashflow Intelligence Engine",
            ParagraphStyle("Sub", parent=style_normal, alignment=1, fontSize=12),
        )
    )
    story.append(PageBreak())

    df_screener = get_screener_data()
    if df_screener.empty:
        logger.error("No screener data found!")
        return

    df_screener = df_screener.sort_values(by="company_id")

    metrics_to_show = [
        "Revenue",
        "Net Profit",
        "EPS",
        "Free Cash Flow",
        "Operating Profit",
        "ROE (%)",
    ]

    companies_processed = 0
    skipped_companies = []

    for idx, row in df_screener.iterrows():
        ticker = row["company_id"]
        comp_name = row.get("company_name_company", ticker)
        sector = row.get("sector_name", "Unknown")

        trends = get_full_trends_data(ticker)

        if trends.empty or len(trends) < 2:
            logger.warning(f"Skipping {ticker} - Insufficient trend data")
            skipped_companies.append(ticker)
            continue

        latest_row = trends.iloc[-1]
        prev_row = trends.iloc[-2]
        latest_year = latest_row["year"]
        prev_year = prev_row["year"]

        story.append(Paragraph(f"<b>{comp_name} ({ticker})</b>", style_header))
        story.append(Paragraph(f"<b>Sector:</b> {sector}", style_normal))
        story.append(Spacer(1, 20))

        table_data = [
            ["Metric", f"Previous ({prev_year})", f"Latest ({latest_year})", "Trend"]
        ]

        for metric in metrics_to_show:
            val_prev = pd.to_numeric(prev_row.get(metric, np.nan), errors="coerce")
            val_latest = pd.to_numeric(latest_row.get(metric, np.nan), errors="coerce")

            trend_str = get_trend_arrow(val_prev, val_latest)

            # Format numbers
            prev_str = f"{val_prev:,.2f}" if pd.notna(val_prev) else "N/A"
            latest_str = f"{val_latest:,.2f}" if pd.notna(val_latest) else "N/A"

            table_data.append(
                [
                    Paragraph(f"<b>{metric}</b>", style_normal),
                    prev_str,
                    latest_str,
                    Paragraph(trend_str, style_normal),
                ]
            )

        t = Table(
            table_data, colWidths=[2.0 * inch, 1.5 * inch, 1.5 * inch, 1.5 * inch]
        )
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f5fa")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#1f497d")),
                    ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                    ("GRID", (0, 0), (-1, -1), 1, colors.lightgrey),
                    ("ALIGN", (1, 1), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]
            )
        )

        story.append(t)
        story.append(PageBreak())
        companies_processed += 1

    try:
        doc.build(story)
        logger.info(
            f"Successfully generated Portfolio Summary for {companies_processed} companies."
        )
        if skipped_companies:
            logger.warning(
                f"Skipped {len(skipped_companies)} companies due to lack of historical data: {', '.join(skipped_companies)}"
            )
    except Exception as e:
        logger.error(f"Failed to build Portfolio Summary PDF: {e}")


if __name__ == "__main__":
    build_portfolio_summary()
